### ISSUE TITLE
pkg_resources.ResolutionError

### ISSUE THREAD

**Issue by whydee86** [sec-it/ComPP#4]
Traceback (most recent call last):
  File "/usr/local/bin/compp", line 4, in <module>
    __import__('pkg_resources').run_script('ComPP==1.0.5', 'compp')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1436, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/compp' not found in metadata at '/home/kali/.local/lib/python3.9/site-packages/ComPP-1.0.5.dist-info'

![image](https://user-images.githubusercontent.com/43274863/151474392-13b4edd7-abad-489a-88b4-01f36091398c.png)

**Comment by whydee86** [comment]
Just remove the pip version and installed manual from github
